# Generated by Django 2.0.6 on 2018-08-13 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0111_auto_20180801_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Childs Complete Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studentgradesinfo',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentGrades'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HP', 'Heart Problem'), ('GP', 'Gastrointestinal Problems'), ('LP', 'Lung Problem'), ('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('CV', 'Convulsion'), ('DP', 'Dermatology Problem'), ('ANE', 'Anemia'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('AST', 'Asthma'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('TP', 'Thyroid Problem'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('0', 'OTHERS'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('92-96', 'A'), ('77-81', 'D'), ('97-100', 'E'), ('82-86', 'AP'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 1', 'G1'), ('GRADE 9', 'G9'), ('TEACH PM', 'TEP'), ('CASA AM', 'CM'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 4', 'G4'), ('PLAY GROUP', 'PG'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('GRADE 5', 'G5'), ('GRADE 8', 'G8'), ('TEACH AM', 'TEA'), ('GRADE 2', 'G2'), ('GRADE 6', 'G6'), ('GRADE 7', 'G7'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 10', 'G10'), ('GRADE 3', 'G3')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
