# Generated by Django 2.0.6 on 2018-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0112_auto_20180813_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('EP', 'Ear Problems'), ('A', 'Allergy'), ('O', 'Others'), ('HMP', 'Hematologic Problem'), ('VP', 'Viral Infection'), ('MP', 'Metabolc Problem'), ('EPL', 'Epilepsy'), ('LP', 'Lung Problem'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('GP', 'Gastrointestinal Problems'), ('ANE', 'Anemia'), ('CV', 'Convulsion'), ('DP', 'Dermatology Problem'), ('HT', 'Hypertension'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('S', 'STOMACH ACHE'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('0', 'OTHERS'), ('C', 'COLDS'), ('V', 'VOMITING'), ('F', 'FEVER'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('76', 'B'), ('92-96', 'A'), ('77-81', 'D'), ('97-100', 'E'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 7', 'G7'), ('GRADE 9', 'G9'), ('GRADE 2', 'G2'), ('GRADE 10', 'G10'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 3', 'G3'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH AM', 'TEA'), ('GRADE 8', 'G8'), ('GRADE 5', 'G5'), ('GRADE 6', 'G6'), ('GRADE 4', 'G4'), ('TEACH PM', 'TEP'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 1', 'G1'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('PLAY GROUP', 'PG'), ('CASA AM', 'CM')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
