# Generated by Django 2.0.6 on 2018-08-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0115_auto_20180827_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG'), ('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('GP', 'Gastrointestinal Problems'), ('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('O', 'Others'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('VP', 'Viral Infection'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('HMP', 'Hematologic Problem'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('F', 'FEVER'), ('CO', 'COUGH'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('77-81', 'D'), ('76', 'B'), ('87-91', 'P'), ('82-86', 'AP'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 10', 'G10'), ('TEACH AM', 'TEA'), ('GRADE 5', 'G5'), ('GRADE 8', 'G8'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM', 'TEP'), ('CASA AM', 'CM'), ('PLAY GROUP', 'PG'), ('GRADE 7', 'G7'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 1', 'G1'), ('GRADE 9', 'G9'), ('GRADE 4', 'G4'), ('GRADE 6', 'G6'), ('GRADE 3', 'G3'), ('GRADE 2', 'G2')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
