# Generated by Django 2.0.6 on 2018-08-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0116_auto_20180828_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('GOOD', 'G'), ('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('CV', 'Convulsion'), ('HMP', 'Hematologic Problem'), ('SZ', 'Seizures'), ('HT', 'Hypertension'), ('AST', 'Asthma'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('EPL', 'Epilepsy'), ('DP', 'Dermatology Problem'), ('EP', 'Ear Problems'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('LP', 'Lung Problem'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('F', 'FEVER'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('82-86', 'AP'), ('97-100', 'E'), ('76', 'B'), ('77-81', 'D'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM GRADE 2', 'TEP-GR2'), ('GRADE 8', 'G8'), ('GRADE 3', 'G3'), ('GRADE 4', 'G4'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 10', 'G10'), ('TEACH PM', 'TEP'), ('GRADE 2', 'G2'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 7', 'G7'), ('GRADE 5', 'G5'), ('GRADE 1', 'G1'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('PLAY GROUP', 'PG'), ('GRADE 9', 'G9'), ('TEACH AM', 'TEA'), ('CASA AM', 'CM')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
