# Generated by Django 2.0.6 on 2018-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0117_auto_20180828_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementaccount',
            name='bookspricetotal_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='modeofpaymentprice_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='musicclassprice_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='notebooks_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='other_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='reservationfee_currency',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='uniforms_currency',
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('CV', 'Convulsion'), ('A', 'Allergy'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('DM', 'Diabetes Mellitus'), ('EPL', 'Epilepsy'), ('ANE', 'Anemia'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('EP', 'Ear Problems'), ('AST', 'Asthma'), ('SZ', 'Seizures'), ('DP', 'Dermatology Problem'), ('VP', 'Viral Infection'), ('HP', 'Heart Problem'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('LP', 'Lung Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('V', 'VOMITING'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('L', 'LBM'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='bookspricetotal',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Books Price Total'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='discount',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Discount Fee'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpaymentprice',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Mode of Payment Price'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='musicclassprice',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Music Class Price'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='notebooks',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Notebook Price'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='other',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Miscellaneous & Others'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='reservationfee',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Reservation Fee'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='uniforms',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Uniform Price'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('77-81', 'D'), ('97-100', 'E'), ('87-91', 'P'), ('82-86', 'AP'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 3', 'G3'), ('GRADE 2', 'G2'), ('TEACH PM', 'TEP'), ('GRADE 5', 'G5'), ('TEACH AM', 'TEA'), ('PLAY GROUP', 'PG'), ('GRADE 7', 'G7'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 9', 'G9'), ('GRADE 10', 'G10'), ('CASA AFTERNOON 1:30', 'CA'), ('CASA AM', 'CM'), ('GRADE 1', 'G1'), ('GRADE 4', 'G4'), ('GRADE 8', 'G8'), ('TEACH PM GRADE 1', 'TEP=GR1')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
