# Generated by Django 2.0.6 on 2018-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0120_auto_20180828_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('VERY GOOD', 'VG'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('EP', 'Ear Problems'), ('SZ', 'Seizures'), ('HT', 'Hypertension'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('ANE', 'Anemia'), ('HP', 'Heart Problem'), ('DP', 'Dermatology Problem'), ('HMP', 'Hematologic Problem'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('DM', 'Diabetes Mellitus'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('C', 'COLDS'), ('CO', 'COUGH'), ('F', 'FEVER'), ('S', 'STOMACH ACHE'), ('H', 'HEADACHE'), ('L', 'LBM'), ('0', 'OTHERS'), ('V', 'VOMITING')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('76', 'B'), ('97-100', 'E'), ('87-91', 'P'), ('82-86', 'AP'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM', 'TEP'), ('GRADE 4', 'G4'), ('PLAY GROUP', 'PG'), ('CASA AM', 'CM'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('TEACH AM', 'TEA'), ('GRADE 3', 'G3'), ('GRADE 10', 'G10'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 7', 'G7'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('GRADE 2', 'G2'), ('GRADE 8', 'G8'), ('GRADE 9', 'G9'), ('GRADE 5', 'G5'), ('GRADE 1', 'G1')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
