# Generated by Django 2.0.6 on 2018-10-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0121_auto_20180828_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='object')),
            ],
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('EP', 'Ear Problems'), ('CV', 'Convulsion'), ('O', 'Others'), ('HMP', 'Hematologic Problem'), ('SZ', 'Seizures'), ('EPL', 'Epilepsy'), ('HT', 'Hypertension'), ('GP', 'Gastrointestinal Problems'), ('AST', 'Asthma'), ('LP', 'Lung Problem'), ('MP', 'Metabolc Problem'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('DP', 'Dermatology Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('0', 'OTHERS'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('87-91', 'P'), ('76', 'B'), ('92-96', 'A'), ('97-100', 'E'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 10', 'G10'), ('TEACH AM', 'TEA'), ('PLAY GROUP', 'PG'), ('GRADE 9', 'G9'), ('GRADE 3', 'G3'), ('GRADE 2', 'G2'), ('GRADE 8', 'G8'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 1', 'G1'), ('GRADE 5', 'G5'), ('GRADE 7', 'G7'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('CASA AM', 'CM'), ('GRADE 4', 'G4'), ('TEACH PM', 'TEP'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 2', 'TEP-GR2')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
