# Generated by Django 2.0.6 on 2018-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0123_auto_20181031_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('O', 'Others'), ('HT', 'Hypertension'), ('CV', 'Convulsion'), ('SZ', 'Seizures'), ('EPL', 'Epilepsy'), ('DM', 'Diabetes Mellitus'), ('DP', 'Dermatology Problem'), ('AST', 'Asthma'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('LP', 'Lung Problem'), ('GP', 'Gastrointestinal Problems'), ('VP', 'Viral Infection'), ('HMP', 'Hematologic Problem'), ('A', 'Allergy'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('L', 'LBM'), ('F', 'FEVER'), ('V', 'VOMITING'), ('S', 'STOMACH ACHE'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('92-96', 'A'), ('76', 'B'), ('97-100', 'E'), ('87-91', 'P'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CASA AM', 'CM'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 1', 'G1'), ('GRADE 5', 'G5'), ('GRADE 8', 'G8'), ('TEACH AM', 'TEA'), ('GRADE 7', 'G7'), ('GRADE 3', 'G3'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM', 'TEP'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('PLAY GROUP', 'PG'), ('GRADE 4', 'G4'), ('GRADE 9', 'G9'), ('GRADE 10', 'G10'), ('GRADE 2', 'G2')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
