# Generated by Django 2.0.6 on 2018-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0124_auto_20181031_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('CASA PROGRAM', 'CASA Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('ANE', 'Anemia'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('O', 'Others'), ('DP', 'Dermatology Problem'), ('AST', 'Asthma'), ('TP', 'Thyroid Problem'), ('EP', 'Ear Problems'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('H', 'HEADACHE'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('92-96', 'A'), ('82-86', 'AP'), ('87-91', 'P'), ('76', 'B'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 4', 'G4'), ('PLAY GROUP', 'PG'), ('GRADE 8', 'G8'), ('GRADE 3', 'G3'), ('GRADE 1', 'G1'), ('CASA AM', 'CM'), ('GRADE 5', 'G5'), ('GRADE 10', 'G10'), ('TEACH AM', 'TEA'), ('GRADE 9', 'G9'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 2', 'G2'), ('TEACH PM', 'TEP'), ('GRADE 6', 'G6'), ('GRADE 7', 'G7'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('CASA AFTERNOON 1:30', 'CA')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
