# Generated by Django 2.0.6 on 2018-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0125_auto_20181031_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('FAIR / PASSED', 'F'), ('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('M', 'Married'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('ANE', 'Anemia'), ('A', 'Allergy'), ('VP', 'Viral Infection'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('O', 'Others'), ('HT', 'Hypertension'), ('HMP', 'Hematologic Problem'), ('MP', 'Metabolc Problem'), ('LP', 'Lung Problem'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('HP', 'Heart Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('L', 'LBM'), ('C', 'COLDS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('92-96', 'A'), ('97-100', 'E'), ('76', 'B'), ('82-86', 'AP'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 9', 'G9'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 8', 'G8'), ('TEACH PM', 'TEP'), ('GRADE 3', 'G3'), ('GRADE 2', 'G2'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 5', 'G5'), ('GRADE 6', 'G6'), ('GRADE 7', 'G7'), ('TEACH AM', 'TEA'), ('GRADE 4', 'G4'), ('GRADE 1', 'G1'), ('PLAY GROUP', 'PG'), ('CASA AM', 'CM'), ('GRADE 10', 'G10')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
