# Generated by Django 2.0.6 on 2018-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0126_auto_20181031_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('EXCELLENT', 'E'), ('GOOD', 'G'), ('FAIR / PASSED', 'F'), ('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HMP', 'Hematologic Problem'), ('O', 'Others'), ('GP', 'Gastrointestinal Problems'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('CV', 'Convulsion'), ('DP', 'Dermatology Problem'), ('TP', 'Thyroid Problem'), ('ANE', 'Anemia'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('A', 'Allergy'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('EP', 'Ear Problems'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('L', 'LBM'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('V', 'VOMITING'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('76', 'B'), ('87-91', 'P'), ('92-96', 'A'), ('97-100', 'E'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 1', 'G1'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH AM', 'TEA'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 6', 'G6'), ('GRADE 7', 'G7'), ('GRADE 2', 'G2'), ('GRADE 3', 'G3'), ('GRADE 9', 'G9'), ('TEACH PM', 'TEP'), ('CASA AM', 'CM'), ('GRADE 5', 'G5'), ('GRADE 8', 'G8'), ('GRADE 10', 'G10'), ('PLAY GROUP', 'PG'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 4', 'G4')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
