# Generated by Django 2.0.6 on 2018-10-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0128_auto_20181031_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U'), ('GOOD', 'G'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('LP', 'Lung Problem'), ('A', 'Allergy'), ('GP', 'Gastrointestinal Problems'), ('HMP', 'Hematologic Problem'), ('TP', 'Thyroid Problem'), ('O', 'Others'), ('AST', 'Asthma'), ('VP', 'Viral Infection'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('ANE', 'Anemia'), ('HP', 'Heart Problem'), ('DP', 'Dermatology Problem'), ('CV', 'Convulsion'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('F', 'FEVER'), ('0', 'OTHERS'), ('S', 'STOMACH ACHE'), ('C', 'COLDS'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('82-86', 'AP'), ('76', 'B'), ('97-100', 'E'), ('92-96', 'A'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM GRADE 1', 'TEP=GR1'), ('CASA AM', 'CM'), ('GRADE 9', 'G9'), ('TEACH PM', 'TEP'), ('PLAY GROUP', 'PG'), ('GRADE 4', 'G4'), ('GRADE 7', 'G7'), ('GRADE 3', 'G3'), ('GRADE 6', 'G6'), ('GRADE 10', 'G10'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH AM', 'TEA'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 1', 'G1'), ('GRADE 8', 'G8'), ('GRADE 2', 'G2'), ('GRADE 5', 'G5')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
