# Generated by Django 2.0.6 on 2018-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0129_auto_20181031_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('FAIR / PASSED', 'F'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('VP', 'Viral Infection'), ('EP', 'Ear Problems'), ('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('CV', 'Convulsion'), ('SZ', 'Seizures'), ('TP', 'Thyroid Problem'), ('O', 'Others'), ('GP', 'Gastrointestinal Problems'), ('EPL', 'Epilepsy'), ('LP', 'Lung Problem'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('DP', 'Dermatology Problem'), ('AST', 'Asthma')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('L', 'LBM'), ('C', 'COLDS'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('92-96', 'A'), ('82-86', 'AP'), ('97-100', 'E'), ('77-81', 'D'), ('76', 'B'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 5', 'G5'), ('PLAY GROUP', 'PG'), ('GRADE 4', 'G4'), ('GRADE 3', 'G3'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 9', 'G9'), ('GRADE 2', 'G2'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH AM', 'TEA'), ('GRADE 1', 'G1'), ('GRADE 10', 'G10'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM', 'TEP'), ('GRADE 8', 'G8'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('CASA AM', 'CM'), ('GRADE 6', 'G6'), ('GRADE 7', 'G7')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
