# Generated by Django 2.0.6 on 2018-11-14 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0130_auto_20181101_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=64, verbose_name='Faculty Name')),
                ('email', models.EmailField(default='example@email.com', max_length=64, verbose_name='Email Address')),
                ('faculty_id', models.IntegerField(default='1234', verbose_name='Faculty ID No.')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('rolegroup', models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Teachers Info',
            },
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='teachersname',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='teachersname',
        ),
        migrations.AddField(
            model_name='students',
            name='lrn_no',
            field=models.CharField(default='', max_length=64, verbose_name='Learners Number'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('SZ', 'Seizures'), ('GP', 'Gastrointestinal Problems'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('ANE', 'Anemia'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('A', 'Allergy'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('CV', 'Convulsion'), ('O', 'Others'), ('EP', 'Ear Problems'), ('VP', 'Viral Infection'), ('AST', 'Asthma'), ('MP', 'Metabolc Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('L', 'LBM'), ('0', 'OTHERS'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('92-96', 'A'), ('97-100', 'E'), ('77-81', 'D'), ('82-86', 'AP'), ('76', 'B'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CASA AFTERNOON 1:30', 'CA'), ('GRADE4', 'G4'), ('GRADE5', 'G5'), ('GRADE1', 'G1'), ('GRADE3', 'G3'), ('GRADE6', 'G6'), ('GRADE7', 'G7'), ('GRADE10', 'G10'), ('CASA AM', 'CM'), ('GRADE9', 'G9'), ('TEACHPM', 'TEP'), ('GRADE2', 'G2'), ('TEACHPM GRADE3', 'TEP-GR3'), ('TEACHPM GRADE1', 'TEP=GR1'), ('GRADE8', 'G8'), ('TEACHAM', 'TEA'), ('PLAY GROUP', 'PG'), ('TEACHPM GRADE2', 'TEP-GR2')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='studentbio',
            name='facultyname',
            field=models.ManyToManyField(to='students.Faculty', verbose_name='Faculty Assigned'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='facultyname',
            field=models.ForeignKey(default='', max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Faculty', verbose_name=' Teachers Name'),
        ),
    ]
