# Generated by Django 2.0.6 on 2018-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0131_auto_20181114_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('ANE', 'Anemia'), ('VP', 'Viral Infection'), ('GP', 'Gastrointestinal Problems'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('DM', 'Diabetes Mellitus'), ('MP', 'Metabolc Problem'), ('A', 'Allergy'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('DP', 'Dermatology Problem'), ('HT', 'Hypertension'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('L', 'LBM'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('76', 'B'), ('87-91', 'P'), ('82-86', 'AP'), ('97-100', 'E'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE8', 'G8'), ('TEACHAM', 'TEA'), ('GRADE7', 'G7'), ('GRADE10', 'G10'), ('GRADE3', 'G3'), ('GRADE5', 'G5'), ('TEACHPM GRADE1', 'TEP=GR1'), ('TEACHPM', 'TEP'), ('TEACHPM GRADE3', 'TEP-GR3'), ('TEACHPM GRADE2', 'TEP-GR2'), ('GRADE6', 'G6'), ('GRADE2', 'G2'), ('CASA AFTERNOON 1:30', 'CA'), ('PLAY GROUP', 'PG'), ('GRADE9', 'G9'), ('CASA AM', 'CM'), ('GRADE1', 'G1'), ('GRADE4', 'G4')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
