# Generated by Django 2.0.6 on 2018-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0132_auto_20181114_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG'), ('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('CV', 'Convulsion'), ('A', 'Allergy'), ('HT', 'Hypertension'), ('GP', 'Gastrointestinal Problems'), ('DM', 'Diabetes Mellitus'), ('LP', 'Lung Problem'), ('MP', 'Metabolc Problem'), ('ANE', 'Anemia'), ('VP', 'Viral Infection'), ('HMP', 'Hematologic Problem'), ('O', 'Others'), ('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('SZ', 'Seizures'), ('AST', 'Asthma')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('F', 'FEVER'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('82-86', 'AP'), ('76', 'B'), ('97-100', 'E'), ('77-81', 'D'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACHPM GRADE2', 'TEP-GR2'), ('GRADE8', 'G8'), ('GRADE6', 'G6'), ('GRADE9', 'G9'), ('GRADE2', 'G2'), ('GRADE5', 'G5'), ('CASA AFTERNOON 1:30', 'CA'), ('PLAY GROUP', 'PG'), ('GRADE4', 'G4'), ('GRADE10', 'G10'), ('GRADE3', 'G3'), ('GRADE7', 'G7'), ('GRADE1', 'G1'), ('TEACHPM GRADE1', 'TEP=GR1'), ('TEACHPM', 'TEP'), ('TEACHAM', 'TEA'), ('TEACHPM GRADE3', 'TEP-GR3'), ('CASA AM', 'CM')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
