# Generated by Django 2.0.6 on 2018-11-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0133_auto_20181114_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('MP', 'Metabolc Problem'), ('DM', 'Diabetes Mellitus'), ('EP', 'Ear Problems'), ('TP', 'Thyroid Problem'), ('A', 'Allergy'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('HP', 'Heart Problem'), ('SZ', 'Seizures'), ('LP', 'Lung Problem'), ('ANE', 'Anemia'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('HMP', 'Hematologic Problem'), ('VP', 'Viral Infection'), ('EPL', 'Epilepsy'), ('CV', 'Convulsion')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('V', 'VOMITING'), ('C', 'COLDS'), ('F', 'FEVER'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('97-100', 'E'), ('77-81', 'D'), ('76', 'B'), ('92-96', 'A'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE4', 'G4'), ('TEACHPM GRADE3', 'TEP-GR3'), ('PLAY GROUP', 'PG'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACHPM GRADE1', 'TEP=GR1'), ('TEACHPM', 'TEP'), ('GRADE1', 'G1'), ('GRADE2', 'G2'), ('GRADE3', 'G3'), ('TEACHPM GRADE2', 'TEP-GR2'), ('GRADE7', 'G7'), ('GRADE5', 'G5'), ('TEACHAM', 'TEA'), ('GRADE10', 'G10'), ('GRADE8', 'G8'), ('GRADE6', 'G6'), ('CASA AM', 'CM'), ('GRADE9', 'G9')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
