# Generated by Django 2.0.6 on 2018-11-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0134_auto_20181114_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('EXCELLENT', 'E')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('EP', 'Ear Problems'), ('O', 'Others'), ('SZ', 'Seizures'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('CV', 'Convulsion'), ('DP', 'Dermatology Problem'), ('VP', 'Viral Infection'), ('LP', 'Lung Problem'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('GP', 'Gastrointestinal Problems'), ('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('ANE', 'Anemia'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('D', 'DIARRHEA'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('77-81', 'D'), ('92-96', 'A'), ('76', 'B'), ('82-86', 'AP'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACHAM', 'TEA'), ('GRADE5', 'G5'), ('GRADE6', 'G6'), ('GRADE10', 'G10'), ('PLAY GROUP', 'PG'), ('TEACHPM GRADE2', 'TEP-GR2'), ('TEACHPM GRADE3', 'TEP-GR3'), ('GRADE4', 'G4'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE2', 'G2'), ('GRADE3', 'G3'), ('GRADE8', 'G8'), ('GRADE9', 'G9'), ('TEACHPM', 'TEP'), ('TEACHPM GRADE1', 'TEP=GR1'), ('GRADE7', 'G7'), ('CASA AM', 'CM'), ('GRADE1', 'G1')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
