# Generated by Django 2.0.6 on 2018-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0135_auto_20181114_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('GP', 'Gastrointestinal Problems'), ('A', 'Allergy'), ('HT', 'Hypertension'), ('EP', 'Ear Problems'), ('MP', 'Metabolc Problem'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('AST', 'Asthma'), ('HMP', 'Hematologic Problem'), ('HP', 'Heart Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('ANE', 'Anemia'), ('LP', 'Lung Problem'), ('O', 'Others'), ('DP', 'Dermatology Problem'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('0', 'OTHERS'), ('F', 'FEVER'), ('CO', 'COUGH'), ('C', 'COLDS'), ('L', 'LBM'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('76', 'B'), ('82-86', 'AP'), ('77-81', 'D'), ('92-96', 'A'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE5', 'G5'), ('GRADE4', 'G4'), ('TEACHPM GRADE3', 'TEP-GR3'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE3', 'G3'), ('GRADE6', 'G6'), ('CASA AM', 'CM'), ('GRADE9', 'G9'), ('TEACHPM', 'TEP'), ('PLAY GROUP', 'PG'), ('GRADE7', 'G7'), ('TEACHPM GRADE2', 'TEP-GR2'), ('TEACHAM', 'TEA'), ('TEACHPM GRADE1', 'TEP=GR1'), ('GRADE10', 'G10'), ('GRADE2', 'G2'), ('GRADE1', 'G1'), ('GRADE8', 'G8')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
