# Generated by Django 2.0.6 on 2018-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0136_auto_20181114_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U'), ('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('LP', 'Lung Problem'), ('AST', 'Asthma'), ('GP', 'Gastrointestinal Problems'), ('DM', 'Diabetes Mellitus'), ('EP', 'Ear Problems'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('MP', 'Metabolc Problem'), ('O', 'Others'), ('HP', 'Heart Problem'), ('SZ', 'Seizures'), ('HMP', 'Hematologic Problem'), ('TP', 'Thyroid Problem'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('ANE', 'Anemia')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('V', 'VOMITING'), ('L', 'LBM'), ('CO', 'COUGH'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL'), ('QRT', 'QUARTERLY')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('92-96', 'A'), ('87-91', 'P'), ('77-81', 'D'), ('76', 'B'), ('82-86', 'AP'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE8', 'G8'), ('GRADE9', 'G9'), ('CASA AM', 'CM'), ('CASA AFTERNOON 1:30', 'CA'), ('TEACHAM', 'TEA'), ('TEACHPM GRADE2', 'TEP-GR2'), ('GRADE3', 'G3'), ('GRADE6', 'G6'), ('TEACHPM GRADE3', 'TEP-GR3'), ('GRADE2', 'G2'), ('TEACHPM GRADE1', 'TEP=GR1'), ('GRADE4', 'G4'), ('GRADE5', 'G5'), ('GRADE7', 'G7'), ('PLAY GROUP', 'PG'), ('GRADE1', 'G1'), ('TEACHPM', 'TEP'), ('GRADE10', 'G10')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
    ]
