# Generated by Django 2.1.2 on 2018-11-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0137_auto_20181114_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsinfo',
            name='fathersname',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='mothersname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='charactersets',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='facultyname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='financialinfo',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='gradeyear',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='applicationtype',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='childsname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fathersname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guardiansname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profilepic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='studentbioidinfo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='studentgradesinfo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='studentname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='students',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='color',
            field=models.CharField(default='#00b35c', max_length=64),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('EXCELLENT', 'E'), ('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HT', 'Hypertension'), ('ANE', 'Anemia'), ('CV', 'Convulsion'), ('AST', 'Asthma'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('MP', 'Metabolc Problem'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('O', 'Others'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('EPL', 'Epilepsy'), ('LP', 'Lung Problem'), ('DM', 'Diabetes Mellitus'), ('DP', 'Dermatology Problem'), ('SZ', 'Seizures'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('H', 'HEADACHE'), ('L', 'LBM'), ('0', 'OTHERS'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('D', 'DIARRHEA'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('87-91', 'P'), ('77-81', 'D'), ('92-96', 'A'), ('97-100', 'E'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACHPM GRADE3', 'TEP-GR3'), ('GRADE7', 'G7'), ('TEACHPM', 'TEP'), ('GRADE9', 'G9'), ('GRADE3', 'G3'), ('CASA AM', 'CM'), ('TEACHPM GRADE2', 'TEP-GR2'), ('GRADE2', 'G2'), ('GRADE10', 'G10'), ('TEACHAM', 'TEA'), ('GRADE4', 'G4'), ('GRADE6', 'G6'), ('TEACHPM GRADE1', 'TEP=GR1'), ('GRADE5', 'G5'), ('PLAY GROUP', 'PG'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE8', 'G8'), ('GRADE1', 'G1')], default='CASA AM', help_text='Choose Group for Students', max_length=64),
        ),
        migrations.DeleteModel(
            name='ParentsInfo',
        ),
        migrations.DeleteModel(
            name='StudentBio',
        ),
    ]
