# Generated by Django 2.1.2 on 2018-11-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0139_auto_20181130_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradegroup',
            options={'verbose_name_plural': 'LGMS Grade Year'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'StudentS  Information'},
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('LP', 'Lung Problem'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('AST', 'Asthma'), ('HMP', 'Hematologic Problem'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('HP', 'Heart Problem'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('V', 'VOMITING'), ('L', 'LBM'), ('CO', 'COUGH'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('77-81', 'D'), ('92-96', 'A'), ('87-91', 'P'), ('76', 'B'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.ForeignKey(help_text='Choose appropriate Group', on_delete=django.db.models.deletion.CASCADE, to='students.GradeGroup'),
        ),
    ]
