# Generated by Django 2.1.2 on 2018-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0143_auto_20181203_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('CV', 'Convulsion'), ('SZ', 'Seizures'), ('GP', 'Gastrointestinal Problems'), ('LP', 'Lung Problem'), ('HMP', 'Hematologic Problem'), ('VP', 'Viral Infection'), ('DP', 'Dermatology Problem'), ('ANE', 'Anemia'), ('A', 'Allergy'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('O', 'Others'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem'), ('AST', 'Asthma'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('V', 'VOMITING'), ('F', 'FEVER'), ('CO', 'COUGH'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('87-91', 'P'), ('97-100', 'E'), ('76', 'B'), ('92-96', 'A'), ('77-81', 'D'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
    ]
