# Generated by Django 2.1.2 on 2018-12-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0145_auto_20181205_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospitalinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='studentname',
            field=models.ForeignKey(default='', max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='illnessinfo',
            name='studentname',
            field=models.ForeignKey(default='', max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='presentcondition',
            name='studentname',
            field=models.ForeignKey(default='', max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('FAIR / PASSED', 'F'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('O', 'Others'), ('EPL', 'Epilepsy'), ('A', 'Allergy'), ('AST', 'Asthma'), ('HMP', 'Hematologic Problem'), ('LP', 'Lung Problem'), ('MP', 'Metabolc Problem'), ('HP', 'Heart Problem'), ('DP', 'Dermatology Problem'), ('DM', 'Diabetes Mellitus'), ('HT', 'Hypertension'), ('VP', 'Viral Infection'), ('EP', 'Ear Problems'), ('CV', 'Convulsion'), ('SZ', 'Seizures'), ('GP', 'Gastrointestinal Problems'), ('TP', 'Thyroid Problem'), ('ANE', 'Anemia')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('F', 'FEVER'), ('C', 'COLDS'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('0', 'OTHERS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('77-81', 'D'), ('87-91', 'P'), ('92-96', 'A'), ('82-86', 'AP'), ('76', 'B')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
    ]
