# Generated by Django 2.1.2 on 2018-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0147_auto_20181205_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('EXCELLENT', 'E'), ('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HT', 'Hypertension'), ('CV', 'Convulsion'), ('O', 'Others'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('MP', 'Metabolc Problem'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('HP', 'Heart Problem'), ('DM', 'Diabetes Mellitus'), ('EP', 'Ear Problems'), ('TP', 'Thyroid Problem'), ('VP', 'Viral Infection'), ('HMP', 'Hematologic Problem'), ('DP', 'Dermatology Problem'), ('A', 'Allergy'), ('AST', 'Asthma'), ('ANE', 'Anemia')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('C', 'COLDS'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('82-86', 'AP'), ('97-100', 'E'), ('87-91', 'P'), ('92-96', 'A'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(blank=True, default='1234', verbose_name='Student ID'),
        ),
    ]
