# Generated by Django 2.1.2 on 2018-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0148_auto_20181205_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('GOOD', 'G'), ('NEEDS IMPROVEMENT', 'NI'), ('FAIR / PASSED', 'F'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('A', 'Allergy'), ('HMP', 'Hematologic Problem'), ('DM', 'Diabetes Mellitus'), ('AST', 'Asthma'), ('HT', 'Hypertension'), ('MP', 'Metabolc Problem'), ('EP', 'Ear Problems'), ('GP', 'Gastrointestinal Problems'), ('DP', 'Dermatology Problem'), ('ANE', 'Anemia'), ('HP', 'Heart Problem'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('VP', 'Viral Infection'), ('TP', 'Thyroid Problem'), ('LP', 'Lung Problem'), ('O', 'Others'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('0', 'OTHERS'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('82-86', 'AP'), ('77-81', 'D'), ('87-91', 'P'), ('92-96', 'A'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(blank=True, verbose_name='Student ID'),
        ),
    ]
