# Generated by Django 2.1.2 on 2018-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0150_auto_20181205_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EPL', 'Epilepsy'), ('DP', 'Dermatology Problem'), ('CV', 'Convulsion'), ('O', 'Others'), ('LP', 'Lung Problem'), ('ANE', 'Anemia'), ('EP', 'Ear Problems'), ('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('MP', 'Metabolc Problem'), ('AST', 'Asthma'), ('TP', 'Thyroid Problem'), ('HMP', 'Hematologic Problem'), ('VP', 'Viral Infection'), ('GP', 'Gastrointestinal Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('V', 'VOMITING'), ('C', 'COLDS'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('87-91', 'P'), ('82-86', 'AP'), ('77-81', 'D'), ('76', 'B'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
    ]
