# Generated by Django 2.1.2 on 2018-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0152_auto_20181205_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('UNSATISFACTORY / FAILED', 'U'), ('GOOD', 'G'), ('FAIR / PASSED', 'F')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('EPL', 'Epilepsy'), ('VP', 'Viral Infection'), ('ANE', 'Anemia'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem'), ('DM', 'Diabetes Mellitus'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('LP', 'Lung Problem'), ('DP', 'Dermatology Problem'), ('HT', 'Hypertension'), ('O', 'Others'), ('AST', 'Asthma'), ('HMP', 'Hematologic Problem'), ('CV', 'Convulsion'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('V', 'VOMITING'), ('L', 'LBM'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('82-86', 'AP'), ('92-96', 'A'), ('76', 'B'), ('87-91', 'P'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Student ID'),
        ),
    ]
