# Generated by Django 2.1.2 on 2018-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0153_auto_20181205_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterbuildingactivities',
            options={'verbose_name_plural': 'LGMS Character Lists'},
        ),
        migrations.AddField(
            model_name='students',
            name='character',
            field=models.ManyToManyField(help_text='Choose list of Characters appropriated', to='students.CharacterBuildingActivities', verbose_name='Character Traits'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U'), ('EXCELLENT', 'E'), ('NEEDS IMPROVEMENT', 'NI'), ('VERY GOOD', 'VG'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('CV', 'Convulsion'), ('MP', 'Metabolc Problem'), ('LP', 'Lung Problem'), ('O', 'Others'), ('SZ', 'Seizures'), ('HP', 'Heart Problem'), ('A', 'Allergy'), ('AST', 'Asthma'), ('GP', 'Gastrointestinal Problems'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('TP', 'Thyroid Problem'), ('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('ANE', 'Anemia'), ('HMP', 'Hematologic Problem'), ('DP', 'Dermatology Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('0', 'OTHERS'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('PLAN D', 'PLAN D - 6 MONTH PAYMENT'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('92-96', 'A'), ('82-86', 'AP'), ('87-91', 'P'), ('77-81', 'D'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
    ]
